[build]
command = "npm install && npm run railway:build"

[deploy]
startCommand = "npm run railway:start"

# Deploy from project root to include !docs folder
[[services]]
name = "backend"
source = "."
startCommand = "cd backend && npm start"

# Environment variables
[deploy.envs]
NODE_ENV = "production"

# Make sure Railway includes all necessary files and doesn't ignore docs
[build.watchIgnore]
# Only ignore actual unnecessary files
"node_modules"
".git"
"frontend/node_modules"
"backend/node_modules"