[build]
command = "npm install --production"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment variables for production
[deploy.envs]
NODE_ENV = "production"

# Optional Shopify configuration
# Uncomment and set these if using Shopify integration:
# SHOPIFY_SHOP_DOMAIN = "your-shop.myshopify.com"
# SHOPIFY_ACCESS_TOKEN = "your-access-token"
# SHOPIFY_API_VERSION = "2024-01"